doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    connections:
        default:
            server: '%env(resolve:MONGODB_URI)%'
            options: {}
            autoEncryption:
                extraOptions:
                    cryptSharedLibPath: '%env(MONGODB_CRYPT_SHARED_LIB_PATH)%'
                    cryptSharedLibRequired: true
                kmsProvider:
                    type: local
                    key: '%env(MONGODB_ENCRYPTION_KEY)%'

    default_database: '%env(resolve:MONGODB_DB)%'

    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: 'App\Document'



